### ISSUE TITLE
Section View: Implement `grid_rows`

### ISSUE THREAD

**Issue by NickChristensen** [j9brown/decluttering-card#1]
**Is your feature request related to a problem? Please describe.**
It doesn't look like `decluttering-card` has implemented `grid_rows` (part of `layout_options`), which controls height in section view. `grid_columns` _does_ work as expected. I've tried adding it to both the template, inside the card object, and in the `decluttering-card` instance itself, neither seems to affect row height.

For example:
```yaml
layout_options:
  grid_columns: 3
  grid_rows: 2
```
Works correctly for the default tile card on left, but not the templated `decluttering-card` on right:
<img width="659" alt="image" src="https://github.com/user-attachments/assets/2a6867f9-59c7-4163-9437-26fd535f44d1">

**Describe the solution you'd like**
In either the template definition or the `decluttering-card` instance, setting `grid_rows` should set the height of the card.

**Comment by NickChristensen** [comment]
I did some further digging and I think the actual issue is `<decluttering-card>`'s `<div id="root">` not expanding to fill the height.

In section mode, the section `.container` div sets a height for each child with `.fit-rows`. This is what the markup structure looks like for a tile card:

```html
<div style="--column-size:3;--row-size:2;" class="card fit-rows "> ← calculated height
  <hui-card>
    <hui-tile-card>
      <ha-card> ← height: 100%, expands to fill .fit-rows div
```

This is what is looks like for a decluttering card:
```html
<div style="--column-size:3;--row-size:2;" class="card fit-rows "> ← calculated height
  <hui-card>
    <decluttering-card>
      <div id="root"> ← no height set
        <hui-tile-card id="declutter-child">
          <ha-card> ← height: 100%, only expands to fill #root
```

**Comment by j9brown** [comment]
Thanks for digging into this.  I wonder if we even need that root div at all.  Hmmm...

**Comment by j9brown** [comment]
Fixed it by removing the div. Everything still seems to work fine but please be on the lookout for any unexpected behavior.
